### ISSUE TITLE
Capturing hw -> Command in sub-process impossible to Stop

### ISSUE THREAD

**Issue by irplus-remote** [bengtmartensson/harctoolboxbundle#254] opened 2018-09-13 15:18 UTC
Sorry for bothering :D Another issue: When i clock on "STOP" Irscrutinizer freezes.

![image](https://user-images.githubusercontent.com/14196521/45497812-f8078100-b778-11e8-9f1d-fa8f7ddfe16e.png)

**Comment by bengtmartensson** [comment] 2018-09-13 15:56
It works for me :-). To troubleshoot many more details are needed. Most likely it is a problem with your system.

Actually, there are so much that can go wrong here -- even though the code as such is correct, at least so I believe. I strongly consider removing it.  And the /dev/lirc interface has gone *so much better*. Any reason you are not using that instead?

**Comment by irplus-remote** [comment] 2018-09-13 16:08
You're right dev/lirc works, i wasnt aware of that, then you might remove it and i guess it's fine

**Comment by bengtmartensson** [comment] 2018-09-14 16:42
The /dev/lirc interface is doing things right. The mode2 stuff an ugly kludge...

To the original problem: since it works for me, and you do not give details for reproducing the problem, there is not much I can do. Most likely it is a problem of your JVM which may have a flawed Process.close or Process.destroy, but that is of course also a guess.

For there reasons. closing.

**Closed by bengtmartensson** 2018-09-14 16:42 UTC

**Comment by irplus-remote** [comment] 2018-09-14 16:45
Btw: im using this nice jvm here: https://www.bell-sw.com/java.html  on RPI

I may suggest to remove that mode completely then if /dev/lirc works? Then it will cause no confusion. Or hide it under some advanced checkbox

**Comment by bengtmartensson** [comment] 2018-09-14 17:28
There is already an (undocumented) command line option `--experimental`, that I may use...
