### ISSUE TITLE
Decoding ambiguity. One and the same signal.

### ISSUE THREAD

**Issue by bakdamir** [bengtmartensson/harctoolboxbundle#336] opened 2019-11-13 18:54 UTC
![image](https://user-images.githubusercontent.com/10049744/68794302-33952800-0668-11ea-9741-b57903e1d010.png)
![image](https://user-images.githubusercontent.com/10049744/68794371-50c9f680-0668-11ea-89af-489642cf8356.png)

**Comment by bengtmartensson** [comment] 2019-11-13 20:01
That one signal has more than one decode is normal and not a bug. It is like "half-full" vs. "half-empty" or that the same tone can be denoted by C sharp or D flat.

Therefore closing.

**Closed by bengtmartensson** 2019-11-13 20:01 UTC
Labels: not a bug, question/support
