### ISSUE TITLE
NullPointerException when exporting remote.

### ISSUE THREAD

**Issue by bakdamir** [bengtmartensson/harctoolboxbundle#235] opened 2018-06-07 03:59 UTC
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.harctoolbox.irscrutinizer.NamedIrSignal$LearnedIrSignalTableModel.checkName(NamedIrSignal.java:307)
	at org.harctoolbox.irscrutinizer.NamedIrSignal$LearnedIrSignalTableModel.checkCommandSanity(NamedIrSignal.java:315)
	at org.harctoolbox.irscrutinizer.NamedIrSignal$LearnedIrSignalTableModel.sanityCheck(NamedIrSignal.java:299)
	at org.harctoolbox.irscrutinizer.NamedIrSignal$LearnedIrSignalTableModel.getCommandsWithSanityCheck(NamedIrSignal.java:276)
	at org.harctoolbox.irscrutinizer.GuiMain.saveCommands(GuiMain.java:1130)
	at org.harctoolbox.irscrutinizer.GuiMain.saveParametricSignals(GuiMain.java:1111)
	at org.harctoolbox.irscrutinizer.GuiMain.parametricOrRawExportButtonActionPerformed(GuiMain.java:7511)
	at org.harctoolbox.irscrutinizer.GuiMain.access$9900(GuiMain.java:84)
	at org.harctoolbox.irscrutinizer.GuiMain$88.actionPerformed(GuiMain.java:3294)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2238)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2296)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4897)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4475)
	at java.awt.Container.dispatchEventImpl(Container.java:2282)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by bengtmartensson** [comment] 2018-06-07 06:20
Please provide information on how this can be reproduced.

**Comment by bakdamir** [comment] 2018-06-07 17:18
![2018-06-07 20-23-38](https://user-images.githubusercontent.com/10049744/41115362-512c7cc8-6a98-11e8-93f1-9fbadabfb990.png)

**Comment by bakdamir** [comment] 2018-06-07 17:37
![2018-06-07 20-23-38](https://user-images.githubusercontent.com/10049744/41112892-3c027a16-6a91-11e8-80ee-76b8f6f7da5d.png)
![2018-06-07 21-36-26](https://user-images.githubusercontent.com/10049744/41116272-e0ad8962-6a9a-11e8-8636-212a822d37e8.png)

**Comment by bengtmartensson** [comment] 2018-06-07 20:16
Thank you very much for the bug report. The problem is the empty command names; this is strictly speaking a user error (or sillyness :-)) but the way the program reacts is of course not acceptable.

Should be fixed by commit 9eb58e6, although the the continuous build has (externally induced) problems. Should be resolve at latest tomorrow (I hope...).

Again, thanx for helping me make IrScrutinizer better!

**Comment by bakdamir** [comment] 2018-06-08 02:52
good approach- "(or sillyness :-))"

**Comment by bengtmartensson** [comment] 2018-06-09 08:36
@bakdamir : still waiting for confirmation that your problem was fixed in the recent snapshot.

**Comment by bakdamir** [comment] 2018-06-09 14:39
Yes, corrected!

**Closed** 2018-06-09 14:39 UTC
Labels: Component: Core, Component: Export, bug
